### ISSUE TITLE
Pressing F1 to unghost or ghost prior to the previos request completing, hangs the client.

### ISSUE THREAD

**Issue by kelkin** [frandallfarmer/neohabitat#208] opened 2017-05-31 02:34 UTC
When unghsoting, if you try to ghost too quickly (prior to your unghost request completing), your client will hang.

**Comment by frandallfarmer** [comment] 2017-06-21 06:03
All the ghost related bugs are due to the same overarching bug...

**Comment by frandallfarmer** [comment] 2018-01-16 22:03
Workaround in place - a dialog tells users to wait. Closing as a duplicate of the command race bug.

**Closed by frandallfarmer** 2018-01-16 22:03 UTC
